sonyxperiadev/device-sony-edo

- rootdir/vendor/etc/init/init.edo.pwr.rc
Write command in android accepts only 2 arguments. That is:
1. File that it will be actually written to.
2. Value to write to this file
If we pass the write command a third argument it will very much complain while building.
If we check the sysfs in kernel for those 2 files they do indeed want 2 arguments to the file.
So make the 2 arguments a string and kernel will handle the splitting.
> init.edo.pwr.rc: Make double arguments into a string

- rootdir/vendor/etc/fstab.edo
This fstab file was based on Kumano which is not
DP platform and thus they were missing.
While at it i included changes from seine fstab.
Such as:
Add metadata partition
Enforce oem_a
Fix USB external storage path
Fix userdata mount flags
> Add dynamic partitions + seine fstab changes

- rootdir/vendor/etc/fstab.edo
On google msm-kernel-4.19 stable branch, these configs is enabled and used by Android 11.
```
CONFIG_FS_ENCRYPTION_INLINE_CRYPT=y
CONFIG_FS_VERITY=y
CONFIG_FS_VERITY_BUILTIN_SIGNATURES=y
```
Since we already upgraded to stock 11, new bootloader require this feature.
We need this flag to decrypt data partition on CAF LA.UM.9.12 kernel with latest bootloader, or decryption will be failed.
> [main] edo: fstab: Enable inlinecrypt flag for data

- platform.mk
Edo is sm8250 and not sm8150.
This is remains from the initial commit as we do our new bring ups based on the closest device trees
which in this case was Kumano (sm8150).
> platform.mk: Change sm8150 to sm8250

- PlatformConfig.mk
Edo platform has dedicated recovery partition so we should
enable building of recovery.img which then can be flashed
on the device.
Also we do not use recovery as boot. If we enable this we
would always boot into recovery.
> PlatformConfig.mk: Enable building of recovery.img

- rootdir/vendor/etc/fstab.edo
The path /dev/block/bootdevice is created after first stage mounts.
At that stage, oem_a is found in /dev/block/by-name
> [EDO] fstab: Fix odm partition path

- rootdir/Android.mk
Devices with Android Dynamic Partitions need a fstab on the
ramdisk root because they don't support system-as-root and
because it is not possible to specify the dynamic partitions
to mount early in the kernel device-tree.
For this reason, it is critical to have a fstab file in the
ramdisk, since it's the only place where we can read it as
per the specifications of the Android Open Source Project (AOSP):
add an entry to the makefile so that we can select this "module"
from our device-specific makefiles.
> [EDO] rootdir: Android.mk: Add entry for fstab on ramdisk root

- rootdir/vendor/etc/init/init.edo.pwr.rc
Fix the params with new ones as found in stock A10.
> [EDO] vendor/init: Fix bus and perf parameters for Kona

- sepolicy_platform/file_contexts
Pretty self-explanatory: the block device address is wrong, and we were missing quite some partitions. Most are not relevant to label, but they have been copy-pasted from Seine regardless.
With these fixes all partitions can be flashed from an enforcing recovery image.
> [EDO] sepolicy: Update block device labels

- platform.mk
This variable is used by device-sony-common to enable rfs
symlinks for the external modem.
> [EDO] platform: Declare TARGET_USES_ESOC

- platform.mk
It makes no sense to generate a kernel panic when the SDX55
modem fails to initialize. Just makes things harder to debug for
no reason.
Let's reset the modem and retry when this happens.
> [EDO] platform: Stop generating kernel panic on SDX55 failure

- platform.mk
We have to compile the libcirrusspkrprot for Sony and to enable
dynamic ECNS and the cirrus path via properties in order to get
speaker output with the CS35L41 amplifiers, found in the entire
EDO project.
> [EDO] platform: Add libcirrusspkrprot and CS35L41 related properties

- rootdir/vendor/ueventd.rc
Another device needed to set up a pincode through gatekeeper:
E spcomlib: [do_ioctl] open() file [/dev/spss_utils] ret [-1] errno [13] [Permission denied]
E spcomlib: [spcom_wait_for_event] after wait event. ret [-13] status [0x00000000] pid [0x077d04f8]
E spcomlib: [spcom_wait_for_sp_link_up] PIL not called !
E KeymasterUtils: SPU is not available
E KeymasterUtils: IsSbKmAvailable failed
E GatekeeperHalDevice: delete_user_legacy
E GatekeeperHalDevice: ret: -45
E GatekeeperHalDevice: resp->status: 0
E spcomlib: [do_ioctl] open() file [/dev/spss_utils] ret [-1] errno [13] [Permission denied]
E spcomlib: [spcom_wait_for_event] after wait event. ret [-13] status [0x00000000] pid [0x077d04f8]
E spcomlib: [spcom_wait_for_sp_link_up] PIL not called !
E KeymasterUtils: SPU is not available
E …
> [EDO] ueventd: Set system user/group on spss_utils

- platform.mk
On SM8250 the ADM buffering is reduced to 2 milliseconds.
> [EDO] platform: Set ADM buffering to 2ms

- rootdir/vendor/etc/audio_platform_info.xml
The unpostfixed `audio_platform_info.xml` file from stock is unaltered
and hence inapplicable to our platform. This is clear from the lack of
SONY audio devices and SENARY_MI2S_RX interface, where our Cirrus AMPs
are connected.
We had the same mismatch on Seine: https://github.com/sonyxperiadev/device-sony-seine/pull/21 :eyes: 
---
Do not merge yet! I still have to clean out the `SONY` devices!
> [EDO] audio_platform_info: Import intcodec from 58.0.A.3.31

- platform.mk
The SPU is loaded by UEFI: this property disables a call to SPCOM
that will try (and fail to) load the SPSS firmware through the spcom library.
Fixes ability to set device PIN (and fingerprint)
> [EDO] [URGENT] platform: Disable SPU for GateKeeper

- sepolicy_platform/genfs_contexts
SM8250 has the same `pm8150[bl]?` as SM8150, at the same address. Import its labels so that our leds and battery info sysfs attributes are properly labeled. Same for the brightness property on the mdss.
> [edo] sepolicy/genfs: Import mdss and spmi labels from Kumano

- PlatformConfig.mk
We previously optimized all the code for CA75, which is..
suboptimal to say the least, since our bigcores are CA77
and even worse - the LITTLE cluster is still based on the
old A55! We were shooting ourselves in our feet performance-wise!
Google also decided to go like this:
TARGET_CPU_VARIANT := generic
TARGET_CPU_VARIANT_RUNTIME := $(big_core_march)
Since there is no CA77 optimization in libbionic yet, set
it to generic until it's fixed on the AOSP end.
Follow the scheme, saving us GIGATONS of disk space (by
reusing generic binaries for all devices).
> PlatformConfig.mk: Switch to generic cpu variant

- sepolicy_platform/genfs_contexts
This subsystem is unlabeled:
I mdm_helper: avc: denied { read } for name="name" dev="sysfs" scontext=u:r:mdm_helper:s0 tcontext=u:object_r:sysfs:s0 tclass=file
I mdm_helper: avc: denied { open } for path="/sys/devices/platform/soc/b0000000.qcom,cnss-qca6390/subsys9/name" dev="sysfs" scontext=u:r:mdm_helper:s0 tcontext=u:object_r:sysfs:s0 tclass=file
> [edo] [R/master] sepolicy/genfs_contexts: Label missing b0000000.qcom,cnss-qca6390 subsys

- platform.mk
`_somc_product` sensor config files are device-specific overlays and differ between PDX203 and PDX206 (to compensate for the LSM6DSM 6DoF IMU and AK0991 magnetometer being mounted at a different orientation).  The targets have been removed from our `common` repo and the files plus copy rules moved to the device repositories.
> [2/4] [R] platform: Stop including (moved) product-specific sensor config overlays

- platform.mk
- rootdir/vendor/etc/sensors/config/kona_ak991x_0_somc_platform.json
- rootdir/vendor/etc/sensors/config/sns_device_orient_somc_platform.json
Complements https://github.com/sonyxperiadev/device-sony-common/pull/852, depends on #42 
---
Without this file a regen of the persistent sensor configuration results in the proximity and ambient light sensor (both provided by the Sensortek 3x3x) to disappear.  The file exists in common with a matching prebuilt build rule, but was simply missed here.
---
These overlays are platform-specific (as indicated by `_somc_platform`) and should not reside in the common repository (unlike SoC specific files, which may or may not be generic depending on future boards). Note that `sns_device_orient_somc_platform` was previously missing entirely.
> [2/2] [R] Include missing kona_stk3x3x_0 sensor file; move Edo-specific (platform) sensor overlays in from common

- sepolicy_platform/file_contexts
These partitions are read by `mdm_helper` and receive a specific `efs_boot_device` label so that _just_ this `mdm_helper` domain is granted read-access.  Addresses the following denials:
denied { search } for comm="ks" name="block" scontext=u:r:mdm_helper:s0 tcontext=u:object_r:block_device:s0 tclass=dir
denied { getattr } for comm="ks" path="/dev/block/sda42" scontext=u:r:mdm_helper:s0 tcontext=u:object_r:block_device:s0 tclass=blk_file
denied { read } for comm="ks" name="sda42" scontext=u:r:mdm_helper:s0 tcontext=u:object_r:block_device:s0 tclass=blk_file
denied { open } for comm="ks" path="/dev/block/sda42" scontext=u:r:mdm_helper:s0 tcontext=u:object_r:block_device:s0 tclass=blk_file
denied { search } for comm="ks" name="block" scontext=u:r:mdm_helper:s0 …
> [R/S] sepolicy: Label mdm partitions as `efs_boot_device`

- PlatformConfig.mk
The msm_drm.blhack_dsi_display0 cmdline hack should only be used if the
bootloader does not set the value for the msm_drm.dsi_display0 cmdline
to be the display panel node name or sets it incorrectly (sets its label
name instead of the actual node name for example). In our case, the Edo
platform bootloader sets the correct value of the msm_drm.dsi_display0
cmdline.
By having this useless hack we run the risk of having a broken display
panel due to its misconfiguration, hence removing this cmdline property
to avoid this behavior.
Signed-off-by: Pavel Dubrova <pashadubrova@gmail.com>
> [r-mr1][URGENT] PlatformConfig: Remove msm_drm.blhack_dsi_display0 cmdline

- platform.mk
- rootdir/vendor/etc/system_properties.xml
Imported from vendor-qcom-opensource-media as of 182649923d3813e2e539a0e36d83b3e70dcfcc4a:
https://github.com/sonyxperiadev/vendor-qcom-opensource-media/tree/182649923d3813e2e539a0e36d83b3e70dcfcc4a
Required for: https://github.com/sonyxperiadev/local_manifests/pull/127
> mediacodec: Import system_properties from CAF.

- platform.mk
In this Pull request we are dropping the non existent  package     android.hardware.bluetooth@1.0-impl-qti as it is already provided in the OEM binaries. 
And the second commit we are switching  to  android.hardware.bluetooth@1.0-service from android.hardware.bluetooth@1.0-service-qti
We are currently using android.hardware.bluetooth@1.0-service-qti which is from Android 9(https://github.com/sonyxperiadev/vendor-qcom-opensource-bluetooth/tree/master/interfaces/bluetooth/1.0/qti)
Let us switch to the android.hardware.bluetooth@1.0-service provided in AOSP, which contains the same service but with updated rc file (https://android.googlesource.com/platform/hardware/interfaces/+/refs/tags/android-14.0.0_r10/bluetooth/1.0/default/)
With this change we can drop vendor/qcom/opensource/Bluetooth
> Bluetooth Fixes
